version: '3'

services:
  mongo-db:
    image: mongo
    ports:
      - 27010:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=needrima
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - db-data:/data/db
  
  mongo-express:
    image: mongo-express
    ports:
      - 8083:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=needrima
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_MONGODB_SERVER=mongo-db

volumes:
  db-data:
    driver: local 